require "spec_helper"

RSpec.describe "date_scopes" do
  pending "#within_days"
  pending "#within_months"
  pending "#within_years"
  pending "#on_day"
  pending "#on_month"
  pending "#on_year"
  pending "#before_day"
  pending "#before_month"
  pending "#before_year"
  pending "#after_day"
  pending "#after_month"
  pending "#after_year"
  pending "#on_or_before_day"
  pending "#on_or_before_month"
  pending "#on_or_before_year"
  pending "#on_or_after_day"
  pending "#on_or_after_month"
  pending "#on_or_after_year"
end
