language: ruby

rvm:
  - 2.1
  - 2.2

env:
  global:
    - CODECLIMATE_REPO_TOKEN=e8dd774ef981922c45a7f04c0e705470ff02101a0bc1fe1992dfe1564f6512e0
  matrix:
    -
    - ACTIVE_RECORD_VERSION=4.0.0
    - ACTIVE_RECORD_VERSION=4.1.0
    - ACTIVE_RECORD_VERSION=4.2.0

script: "bundle exec rake spec"

branches:
  only:
    - master
